### ISSUE TITLE
Migration to Coq 8.6?

### ISSUE THREAD

**Issue by jeehoonkang** [vafeiadis/hahn#2]
Dear Viktor,

I am migrating the promising semantics Coq model (https://github.com/snu-sf/promising-coq) from Coq 8.5 to 8.6.  As it depends on hahn, I wonder if you have a plan to migrate hahn to 8.6.  I tried myself but I couldn't leave the proof style untouched, and cannot help making the proof longer..

**Comment by vafeiadis** [comment]
I migrated it: only two minor changes were needed.
